blueprint:
  name: Dimmer Two Button
  description: Control a dimmable light with two binary sensors (up/down buttons).
  domain: automation
  source_url: https://raw.githubusercontent.com/jacobmr/blueprints/main/dimmer_two_button.yaml
  input:
    up_button:
      name: Up Button
      selector:
        entity:
          domain: binary_sensor
    down_button:
      name: Down Button
      selector:
        entity:
          domain: binary_sensor
    target_light:
      name: Target Light
      selector:
        entity:
          domain: light

mode: parallel
variables:
  up_button: !input up_button
  down_button: !input down_button
  target_light: !input target_light

trigger:
  - platform: state
    entity_id: !input up_button
    to: 'on'
    id: up_press
  - platform: state
    entity_id: !input down_button
    to: 'on'
    id: down_press
  - platform: state
    entity_id: !input up_button
    from: 'on'
    to: 'off'
    id: up_release
  - platform: state
    entity_id: !input down_button
    from: 'on'
    to: 'off'
    id: down_release

condition: []

action:
  - choose:
      - conditions:
          - condition: trigger
            id: up_press
        sequence:
          - choose:
              - conditions:
                  - condition: state
                    entity_id: !input target_light
                    state: 'off'
                sequence:
                  - service: light.turn_on
                    data:
                      entity_id: !input target_light
                      brightness_pct: 10
              - conditions:
                  - condition: state
                    entity_id: !input target_light
                    state: 'on'
                sequence:
                  # Wait briefly to detect tap vs hold
                  - delay: '0:00:00.4'
                  - if:
                      - condition: state
                        entity_id: !input up_button
                        state: 'on'
                    then:
                      # Still pressed after 400ms = HOLD, start dimming loop
                      - service: script.dimming_loop
                        data:
                          target_light: !input target_light
                          direction: 'up'
                    else:
                      # Released within 400ms = TAP, increase brightness by 10%
                      - service: light.turn_on
                        data:
                          entity_id: !input target_light
                          brightness_step_pct: 10

      - conditions:
          - condition: trigger
            id: down_press
        sequence:
          - choose:
              - conditions:
                  - condition: state
                    entity_id: !input target_light
                    state: 'off'
                sequence: []
              - conditions:
                  - condition: state
                    entity_id: !input target_light
                    state: 'on'
                sequence:
                  # Wait briefly to detect tap vs hold
                  - delay: '0:00:00.4'
                  - if:
                      - condition: state
                        entity_id: !input down_button
                        state: 'on'
                    then:
                      # Still pressed after 400ms = HOLD, start dimming loop
                      - service: script.dimming_loop
                        data:
                          target_light: !input target_light
                          direction: 'down'
                    else:
                      # Released within 400ms = TAP, turn off
                      - service: light.turn_off
                        data:
                          entity_id: !input target_light

      - conditions:
          - condition: trigger
            id: up_release
        sequence:
          - service: script.turn_off
            target:
              entity_id: script.dimming_loop

      - conditions:
          - condition: trigger
            id: down_release
        sequence:
          - service: script.turn_off
            target:
              entity_id: script.dimming_loop
