blueprint:
  name: SPST Switch Light Control
  description: Control a light with a regular SPST (single-pole single-throw) switch. Switch ON = Light ON, Switch OFF = Light OFF. No hold or double-click detection.
  domain: automation
  source_url: https://raw.githubusercontent.com/jacobmr/blueprints/main/spst_switch_light.yaml
  input:
    switch_sensor:
      name: SPST Switch
      description: Binary sensor representing the physical SPST switch state
      selector:
        entity:
          domain: binary_sensor
    target_light:
      name: Target Light
      selector:
        entity:
          domain: light

mode: single
max_exceeded: silent

variables:
  switch_sensor: !input switch_sensor
  target_light: !input target_light

trigger:
  - platform: state
    entity_id: !input switch_sensor
    to: 'on'
    id: switch_on
  - platform: state
    entity_id: !input switch_sensor
    to: 'off'
    id: switch_off

condition: []

action:
  - choose:
      # ============ SWITCH ON = LIGHT ON ============
      - conditions:
          - condition: trigger
            id: switch_on
        sequence:
          - service: light.turn_on
            target:
              entity_id: !input target_light

      # ============ SWITCH OFF = LIGHT OFF ============
      - conditions:
          - condition: trigger
            id: switch_off
        sequence:
          - service: light.turn_off
            target:
              entity_id: !input target_light
