blueprint:
  name: SPST Switch Light Control
  description: Control a light with a regular SPST (single-pole single-throw) switch. Switch ON = Light ON, Switch OFF = Light OFF. No hold or double-click detection.
  domain: automation
  source_url: https://raw.githubusercontent.com/jacobmr/blueprints/main/spst_switch_light.yaml
  input:
    switch_sensor:
      name: SPST Switch
      description: Binary sensor representing the physical SPST switch state
      selector:
        entity:
          domain: binary_sensor
    target_light:
      name: Target Light
      selector:
        entity:
          domain: light
    upside_down:
      name: Switch is Upside Down (oops)
      description: Check this if the switch is installed upside down - inverts the on/off logic
      default: false
      selector:
        boolean:

mode: single
max_exceeded: silent

variables:
  switch_sensor: !input switch_sensor
  target_light: !input target_light
  upside_down: !input upside_down

trigger:
  - platform: state
    entity_id: !input switch_sensor
    to: 'on'
    id: switch_on
  - platform: state
    entity_id: !input switch_sensor
    to: 'off'
    id: switch_off

condition: []

action:
  - choose:
      # ============ TURN LIGHT ON ============
      - conditions:
          - condition: or
            conditions:
              # Normal: switch ON = light ON
              - condition: and
                conditions:
                  - condition: trigger
                    id: switch_on
                  - condition: template
                    value_template: "{{ not upside_down }}"
              # Inverted: switch OFF = light ON
              - condition: and
                conditions:
                  - condition: trigger
                    id: switch_off
                  - condition: template
                    value_template: "{{ upside_down }}"
        sequence:
          - service: light.turn_on
            target:
              entity_id: !input target_light

      # ============ TURN LIGHT OFF ============
      - conditions:
          - condition: or
            conditions:
              # Normal: switch OFF = light OFF
              - condition: and
                conditions:
                  - condition: trigger
                    id: switch_off
                  - condition: template
                    value_template: "{{ not upside_down }}"
              # Inverted: switch ON = light OFF
              - condition: and
                conditions:
                  - condition: trigger
                    id: switch_on
                  - condition: template
                    value_template: "{{ upside_down }}"
        sequence:
          - service: light.turn_off
            target:
              entity_id: !input target_light
