blueprint:
  name: Two Button On/Off
  description: Simple on/off control with two binary sensors. UP button turns light ON, DOWN button turns light OFF. No dimming or double-click detection.
  domain: automation
  source_url: https://raw.githubusercontent.com/jacobmr/blueprints/main/two_button_onoff.yaml
  input:
    up_button:
      name: Up Button (ON)
      description: Press this button to turn the light ON
      selector:
        entity:
          domain: binary_sensor
    down_button:
      name: Down Button (OFF)
      description: Press this button to turn the light OFF
      selector:
        entity:
          domain: binary_sensor
    target_light:
      name: Target Light
      selector:
        entity:
          domain: light

mode: single
max_exceeded: silent

variables:
  up_button: !input up_button
  down_button: !input down_button
  target_light: !input target_light

trigger:
  - platform: state
    entity_id: !input up_button
    to: 'on'
    id: up_press
  - platform: state
    entity_id: !input down_button
    to: 'on'
    id: down_press

condition: []

action:
  - choose:
      # ============ UP BUTTON = TURN ON ============
      - conditions:
          - condition: trigger
            id: up_press
        sequence:
          - service: light.turn_on
            target:
              entity_id: !input target_light

      # ============ DOWN BUTTON = TURN OFF ============
      - conditions:
          - condition: trigger
            id: down_press
        sequence:
          - service: light.turn_off
            target:
              entity_id: !input target_light
